# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cutword_rpc.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='cutword_rpc.proto',
  package='cutword',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x11\x63utword_rpc.proto\x12\x07\x63utword\"\x14\n\x04\x44\x61ta\x12\x0c\n\x04text\x18\x01 \x01(\t2.\n\x03\x43ut\x12\'\n\x05\x44oCut\x12\r.cutword.Data\x1a\r.cutword.Data\"\x00\x62\x06proto3')
)




_DATA = _descriptor.Descriptor(
  name='Data',
  full_name='cutword.Data',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='text', full_name='cutword.Data.text', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=50,
)

DESCRIPTOR.message_types_by_name['Data'] = _DATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Data = _reflection.GeneratedProtocolMessageType('Data', (_message.Message,), {
  'DESCRIPTOR' : _DATA,
  '__module__' : 'cutword_rpc_pb2'
  # @@protoc_insertion_point(class_scope:cutword.Data)
  })
_sym_db.RegisterMessage(Data)



_CUT = _descriptor.ServiceDescriptor(
  name='Cut',
  full_name='cutword.Cut',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=52,
  serialized_end=98,
  methods=[
  _descriptor.MethodDescriptor(
    name='DoCut',
    full_name='cutword.Cut.DoCut',
    index=0,
    containing_service=None,
    input_type=_DATA,
    output_type=_DATA,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_CUT)

DESCRIPTOR.services_by_name['Cut'] = _CUT

# @@protoc_insertion_point(module_scope)
